### ISSUE TITLE
BUG: First Character Is Always Lowercase

### ISSUE THREAD

**Issue by TeaBizzy** [waterrmalann/padlock#6]
When generating a password using every method except random string. The first letter is ALWAYS lowercase after switching the generation method when Uppercase is set to true, and Lowercase is set to false.

Steps to recreate:
1.Set generation method to XKCD, Psuedoword Method, or Psuedoword + Passphrase Method.
2. Set upper case to true.
3. Set lowercase to false.
![Screenshot from 2022-09-13 09-00-01](https://user-images.githubusercontent.com/111951212/189907787-402c8fe3-60dc-4637-883f-9a9a43c14fea.png)

**Comment by waterrmalann** [comment]
After some brief confusion, I've figured out the root cause. 

This seems to be an issue with the [munge()](https://github.com/waterrmalann/padlock/blob/409a7732912c6a648cd391fe454b2d074201b7fa/js/main.js#L283) function at the part where it has to loop over the characters to shift cases, the loop actually starts at index position 1 and not 0 so the first character always remained lowercase as it was not munged. 

I can't exactly remember why I did this at the time but I think it was intentional as the first letter was always meant to be substituted with something else (numbers or symbols) and so didn't need to be part of the case shifting loop but I probably failed to realize that a substitution for the first character would not always be available and it would cause this side effect.

I've pushed a [fix to this](https://github.com/waterrmalann/padlock/commit/34358eebfacd5a7f101290c14abf625b1df0bdef) by starting the loop from index position 0 instead of 1.
